### ISSUE TITLE
Clean up project for 1.0 release

### ISSUE THREAD

**Issue by sergei-maertens** [django-commons/django-cookie-consent#108]
Let's make the 1.0 release a neat and tidy one.

**Tasks**

- [x] Delete legacy cookiebar (`static/cookiebar.js`)
- [x] Delete deprecated template tags
- [x] Check code files for style & make them pass flake8
- [x] Check which functionality may be obsolete
- [x] Add Django 5.0 support (it'll probably be released by then)
- [x] Drop Django 3.2 support
