### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by sergei-maertens** [django-commons/django-cookie-consent#98]
Link to project board: https://github.com/orgs/jazzband/projects/13/views/1

---

Now that 0.4.0 is released to PyPI and the most pressing matters are resolved, we can look ahead to the future and get a stable version published.

There is a [milestone](https://github.com/jazzband/django-cookie-consent/milestone/2) for the 1.0 release and any issues that must be resolved before that release are attached to it.

**Note** that jumping from the `0.x.y` versioning scheme to `1.0.z` allows for introducing breaking changes. The breaking changes towards 1.0 will likely require updating your code, but we should aim to do these as soon as possible if they are needed to get them out of the way.

Breaking changes after that will require a bump to `2.0`, `3.0` etc.. Dropping support for no-longer maintained Django versions technically qualifies as a breaking change, so we will handle them as such. Those changes typically won't require you updating your code. If, however, we do introduce future breaking changes, they will be clearly communicated.

Now, for the roadmap - these are roughly the goals/reworks that must be completed before we can publish 1.0

* [x] ~~Solving the Javascript integration properly (#15, #49). In short, there should probably be a move towards a JSON view for async fetching of the cookie groups/configuration and rewrite the cookiebar JS (and supporting JS) to handle this. Inline JS is annoying in general in combination with Content-Security-Policy too, so in general this should be a good move.~~  Please try 0.5.0b0 and report back your experiences!
* [x] ~~Scripting cleanup and tooling: ideally, people should be able to drop the shipped scripts/modules in Webpack or their bundler/toolchain of choice. I'd also like to explore `<script type="module" ... />` to support modern browsers. This may not drop support for simple staticfiles integration and will still be available. We may set up a bit more of a toolchain for JS (and possibly look into Typescript so we can also ship types for users on a typescript toolchain).~~ Modules are now available in 0.5.0b0, but integrating in your frontend toolchain depends on ideas/feedback from the community.
* [x] Fixture support (for moving between staging/prod environment) via natural primary key #103
* [x] Good defaults but extensible architecture - see #34

**Comment by fabienheureux** [comment]
@sergei-maertens are there people actively working on this project ?

**Comment by sergei-maertens** [comment]
> @sergei-maertens are there people actively working on this project ?

I definitely am! Of course I'm distributing my time over a couple of projects, so my development work is typically in bursts

**Comment by fabienheureux** [comment]
That is great to hear, I am using it on production on a project. 
Are there any area of the roadmap that you need help with ?

**Comment by sergei-maertens** [comment]
I think a critical look at the docs wouldn't hurt and checking if we can
clean up the implementation of backend code.

The Big Thing is really the JS support at the moment which I'd like to sort
out myself, but I can always use people to test it out!

**Comment by sergei-maertens** [comment]
@fabienheureux I've been ticking off some items and that resulted in a couple more issues on the backlog with concrete tasks.

Either way, the [good first issue](https://github.com/jazzband/django-cookie-consent/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) filter has some easy-pickings, and the [milestone](https://github.com/jazzband/django-cookie-consent/milestone/2) issues also have some less-straightforward things if you're comfortable with that.

I will assign the issues to myself that are being covered with the JS rework so it's clear they're being worked on :) Feel free to pick up anything else if you'd like!
